DROP TABLE IF EXISTS "product_materials";
DROP TABLE IF EXISTS "products";

CREATE TABLE "products" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "product_materials" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" BIGINT NOT NULL,
    "material" VARCHAR(255) NOT NULL,
    "quantity" INT NOT NULL,
    CONSTRAINT "fk_product_material_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id")
);
